@api = http://localhost:5000

POST {{api}}/login
Content-Type: application/json

{
    "username": 123,
    "password": 123
}

###
GET {{api}}/user/profile
auth_token: 

###
GET {{api}}/token

###
POST {{api}}/token
CSRF-Token: tzGe7wsF-JRv4VNdJAhqUIk33abEZ2E0dOso

###
GET {{api}}/login

###
GET {{api}}/signup

###
POST {{api}}/register
Content-Type: application/json

{
    "username": "totoypogi123",
    "password": "123",
    "email": "andrewmoquia09@gmail.com",
    "confirmPassword": "123"
}

###
POST {{api}}/login
Content-Type: application/json

{
    "email": "totoypogi123@gmail.com",
    "password": "totoypogi123"
}

###
GET {{api}}/


###
GET {{api}}/user

###
GET {{api}}/logout

###
GET {{api}}/register
