@api = http://localhost:3000

POST {{api}}/login
Content-Type: application/json

{
    "username": 123,
    "password": 123
}

###
GET {{api}}/user/profile
auth_token: 

###
GET {{api}}/token

###
POST {{api}}/token
CSRF-Token: tzGe7wsF-JRv4VNdJAhqUIk33abEZ2E0dOso

###
GET {{api}}/login

###
GET {{api}}/signup


###
POST {{api}}/signup
CSRF-Token: Cx0J5Yzx-st94Z08zkrkl5Y0NH-zqhZV3NCk
Content-Type: application/json

{
    "username": "totoypogi",
    "password": "totoypogi123",
    "email": "totoypogi123@gmail.com",
    "confirmPassword": "totoypogi123"
}

###
POST {{api}}/login
Content-Type: application/json

{
    "email": "totoypogi123@gmail.com",
    "password": "totoypogi123"
}

###
GET {{api}}/


###
GET {{api}}/user

###
GET {{api}}/logout